messages:
  noPermission: "&cNie Posiadasz uprawnień do tej komendy (hikemc.wallet.admin)"
  adminAddWallet: "&8» &aPomyślnie dodałeś &2{kwota} zł &adla &2{target}" # Użyj: {admin} - nick administratora, {kwota} - jaka kwota, {target} - nick osoby któej admin ustawia
  playerAddWallet: "&8» &aAdministrator &2{admin} &adał ci &2{kwota} zł" # Użyj: {admin} - nick administratora, {kwota} - jaka kwota, {target} - nick osoby któej admin ustawia
  adminRemoveWallet: "&8» &cPomyślnie zabrałeś &4{kwota} zł &cdla &4{target}" # Użyj: {admin} - nick administratora, {kwota} - jaka kwota, {target} - nick osoby któej admin ustawia
  playerRemoveWallet: "&8» &cAdministrator &4{admin} &czabrał ci &4{kwota} zł" # Użyj: {admin} - nick administratora, {kwota} - jaka kwota, {target} - nick osoby któej admin ustawia
  adminSetWallet: "&8» &7Ustawiłeś &6{kwota} zł &7dla &6{target}" # Użyj: {admin} - nick administratora, {kwota} - jaka kwota, {target} - nick osoby któej admin ustawia
  playerSetWallet: "&8» &7Administrator &e{admin} &7ustawił ci portfel na &e{kwota} zł" # Użyj: {admin} - nick administratora, {kwota} - jaka kwota, {target} - nick osoby któej admin ustawia
  poprawneUzycie: "&7Poprawne użycie: &a/aportfel (NICK) (ADD/REMOVE/SET) (KWOTA)"
  playerOffline: "&cPodany gracz jest offline!"
  noPermissionReload: "&CNie posiadasz uprawnień do tego!"
  reloadSuccess: "&aPomyślnie przeładowano konfiguracje pluginu HikeWallet"


permissions:
  adminPermission: "hikemc.wallet.admin"
  portfelPermission: "hikemc.wallet"
  reloadPermission: "hikemc.wallet.reload"


database:
  url: jdbc:mysql://HOST/DATABASENAME
  username: USERNAME
  password: PASSWROD
# uzupełnij danymi z bazy danych

sklep-gui:
  # Title gui
  gui-name: "&cwPLN sklep"
  # Od 9 do 54
  gui-size: 36
  # Itemy w gui


  # Nazwa - Nazwa itemu w gui (Tekst, nazwa itemu)
  # Material - Item np. PAPER (String material, Material jako tekst, "spacje" zastepuj znakiem "_", wszystkie litery muszą być duże, z capslokiem)
  # Opis - Lore itemu, opis jaki masz pod itemem (Tekst, opis przedmiotu, napis z cena pojawia sie automatycznie), przyklad jak to wyglada:
  # Twoj tekst 1
  # Twoj tekst 2
  # Cena: 10 wPLN


  # Cena - Cena itemu za wPLN (Wirtualne pieniadze) (Cyfra, np. 2.0)
  # Slot - Slot w gui (Cyfra)
  item-1:
    nazwa: ""
    material:
    opis:
      linia1:
      linia2:
    cena:
    slot:
  item-2:
    nazwa: ""
    material:
    opis:
      linia1:
      linia2:
    cena:
    slot:
  item-3:
    nazwa: ""
    material:
    opis:
      linia1:
      linia2:
    cena:
    slot:
  item-4:
    nazwa: ""
    material:
    opis:
      linia1:
      linia2:
    cena:
    slot:
  item-5:
    nazwa: ""
    material:
    opis:
      linia1:
      linia2:
    cena:
    slot:
  item-6:
    nazwa: ""
    material:
    opis:
      linia1:
      linia2:
    cena:
    slot:


