name: PetaPorfel
version: '1.0.4'
main: eu.hikemc.Main
api-version: '1.16'
author: podateK_
softdepend: [PlaceholderAPI]
website: https://pl.hikemc.eu
commands:
  aportfel:
      description: Komendy admina
  portfel:
      description: Komendy gracza
  petaportfel-reload:
    description: Komenda do przeładowania configu
  wplnsklep:
    description: Komenda do otwarcia sklepu do wydawania wpln!